version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./shared:/app/shared
      - ./data:/app/data
    environment:
      - PORT=8080
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./shared:/app/shared
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  shared_data:
