info:
  contact: {}
paths:
  /v0.1/parking/{projectId}/train-images:
    post:
      description: |
        ■ errCode with 400
        PARAM_BAD : 파라미터 오류

        ■ errCode with 500
        INTERNAL_SERVER : 내부 로직 처리 실패
        INTERNAL_DB : DB 처리 실패
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: 학습 이미지 업로드
      tags:
      - parking
swagger: "2.0"
